<a href="https://colab.research.google.com/github/Niraj-Ramnani/Lab-Record-6th-sem/blob/main/ML%20lab/program10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array(([2,9],[1,5],[3,6]),dtype=float)
y = np.array(([92],[86],[89]),dtype=float)
x = x/np.amax(x,axis=0)
y = y/100

In [ ]:
x

array([[0.66666667, 1.        ],
       [0.33333333, 0.55555556],
       [1.        , 0.66666667]])

In [ ]:
y

array([[0.92],
       [0.86],
       [0.89]])

In [ ]:
def sigmoid(x):
  return 1/(1 + np.exp(-x))
def sigmoid_grad(x):
  return x * (1-x)

In [ ]:
epoch = 1000
eta = 0.2
input_neurons = 2
hidden_neurons = 3
output_neurons = 1


In [ ]:
wh = np.random.uniform(size=(input_neurons,hidden_neurons))
bh = np.random.uniform(size=(1,hidden_neurons))
wout=np.random.uniform(size=(hidden_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))


In [ ]:
for i in range(epoch):
  h_ip = np.dot(x,wh) + bh
  h_act = sigmoid(h_ip)
  o_ip = np.dot(h_act,wout) + bout
  output = sigmoid(o_ip)
  Eo = y -output
  outgrad = sigmoid_grad(output)
  d_output = Eo * outgrad
  Eh = d_output.dot(wout.T)
  hiddengrad = sigmoid_grad(h_act)
  d_hidden = Eh * hiddengrad
  wout += h_act.T.dot(d_output) * eta
  wh += x.T.dot(d_hidden) * eta


In [ ]:
print("Normalized Input:\n",str(x))
print("Actual Output:\n",str(y))
print("Predicted Output:\n",output)

Normalized Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.89631814]
 [0.88019629]
 [0.8932312 ]]
